Repository metrico/qryn-view, pull requests merged in 2022-12, with the labels that each got.

#191 Fixed ordering of data views
  src/components/DataViews/index.js
Labels: enhancement

#221 fix: Label Browser will open upon Keypressup #219
  src/components/LabelBrowser/components/QueryBar.js
Labels: Labels

#223 fix: Label Browser Button #220
  src/components/LabelBrowser/components/LabelsSelector/LabelsList.js
  src/components/LabelBrowser/components/LabelsSelector/ValuesSelector.js
Labels: bug, Labels

#224 Fix share link
  src/components/DataViews/components/QueryBuilder/hooks/index.tsx
  src/components/StatusBar/components/copylinkbutton/CopyLinkButton.js
  src/components/StatusBar/components/copylinkbutton/CopyLinkButton.tsx
  src/components/StatusBar/components/copylinkbutton/components/CopyButton.tsx
  src/components/StatusBar/components/copylinkbutton/components/RelativeTimeMenu.tsx
  src/components/StatusBar/components/copylinkbutton/helpers/index.js
  src/components/StatusBar/components/copylinkbutton/helpers/index.ts
  src/components/StatusBar/components/copylinkbutton/hooks/index.tsx
  src/components/StatusBar/components/copylinkbutton/styles/index.tsx
  src/components/StatusBar/components/daterangepicker/index.js
  src/components/StatusBar/styled/index.js
  src/plugins/queryhistory/index.js
  src/plugins/settingsmenu/Menu.js
  src/theme/styles/Button.js
Labels: bug, enhancement
